### ISSUE TITLE
"Submit Talk" and "Financial Aid" submission links are still active on the web site

### ISSUE THREAD

**Issue by FlipperPA** [djangocon/2016.djangocon.us#104]
See here: https://2016.djangocon.us/ "We’re recruiting new speakers for a wide range of talks. There will be something for everybody! Submit your talk today!"

And here: 

https://2016.djangocon.us/speaking/
- "The deadline for submissions is April 18. Apply now!"
- "Fill out the Financial Aid application by April 25!"

And here: https://2016.djangocon.us/financialaid/
- March 15, 2016: Financial aid application opens

I'll be taking care of any that can be addressed through the CMS, but not sure about the front page...

**Comment by jefftriplett** [comment]
👍 Thank you! I'll get the home page. We had a meeting about it yesterday, but didn't quite get past troubleshooting postgres on Mac issues. /me adds to my list

**Comment by FlipperPA** [comment]
If you want, I can issue a PR later today so you have one less thing to do. I've taken care of the other pages, put things in the past tense and removed links, etc.

**Comment by jefftriplett** [comment]
I will never turn down that offer! Thank you.

**Comment by williln** [comment]
Thanks @FlipperPA!
