### ISSUE TITLE
Moar easter eggs

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#106]
Last year we had https://2015.djangocon.us/404/ and several others. We need moar of these.

**Comment by williln** [comment]
Suggestions: 

- Fun 404 
- Fun 500 
- Emoji mode 
- Something something Django ponies?

**Comment by jefftriplett** [comment]
@mightym just in case you get bored. We had this gem last year: https://2015.djangocon.us/500/
