### ISSUE TITLE
SSL Mixed Content Warning from Font CSS

### ISSUE THREAD

**Issue by Miserlou** [djangocon/2016.djangocon.us#109]
The CSS has import which points to "http://fast.fonts.net/t/1.css?apiType=css&projectid=59d67ea6-c9ee-4e4b-9993-40a9b28e0c96", so it gets blocked by Firefox. This should be changed to https://

**Comment by Miserlou** [comment]
Actually, that file doesn't seem to contain anything anyway, maybe this line can simply be removed?

**Comment by mightym** [comment]
That "pseudo" import is need for using the webfonts of fonts.com. I guess by importing/calling that file they just verify the ID and the domain of that project. I changed it to https. fonts.com doesn't explicit give the option to use https there, but it seems to work :)

**Comment by jefftriplett** [comment]
👍  thanks for letting us know @Miserlou
