### ISSUE TITLE
Styleguide?

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#11]
My original issue which in hindsight, I worded poorly:

> Would a style guide or something akin to this be useful? http://www.markitdown.net/markdown

What I meant to say was should we create a page with examples of all of the text styles in place so that we can troubleshoot potential style issues. This way we see all of the heading styles, bold elements, bullets, etc.

**Comment by b3h3rkz** [comment]
Yes!!!
I have used this one before, really cool.
https://pypi.python.org/pypi/django-markdown

**Comment by KatherineMichel** [comment]
I like it, but think it could be looked at in the larger picture of making the project user friendly in general, for instance, some other things that could be considered to be added...
license (if going to be used)
emoji key
if style guide is created, PEP 8 could be referenced too
Any special contributing info
Making README info clear and accurate

**Comment by jefftriplett** [comment]
@KatherineMichel great points. I think the project could benefit from this.

I bet [PinaxCon](https://github.com/pinax/PinaxCon) could too which is upstream and what we sort-of started with.

Would you want to help with the points you mentioned?

**Comment by KatherineMichel** [comment]
Of course, I'll help :) I can help with..
- Emoji Key 
- Making README clear and accurate
- Can add license, if interested (looks like was MIT License for Django Software Foundation) in past
For the others, (style guide, contributing info) can probably help too

**Comment by williln** [comment]
@KatherineMichel Thank you! You're awesome :-)

**Comment by jefftriplett** [comment]
@KatherineMichel that's great! :)

I added the BSD 3-Clause License (same as the DSF's website uses) via [#81f833fc](https://github.com/djangocon/2016.djangocon.us/commit/81f833fc9af5e5525861d6e3539eb0ee49d78a34). If MIT is more appropriate then I'm game too.

Feel free to send PR's for the rest or ping me in Slack if you have questions.

Also, to echo what @williln said, thank you! You're awesome! :)

**Comment by KatherineMichel** [comment]
Thank you, just submitted a pull request for development branch README. Hopefully looks good. I got sidetracked watching an excellent series of Swift videos in Code School Free Weekend. The only other thing I can think of right now is to change the format of contributors so are smaller entries. Maybe that is moot. Kent Hobbs did that with https://github.com/kentcdodds/all-contributors/blob/master/README.md. Could think about doing that later, especially if more people contribute. I will think about style guide and contributing info too.

**Comment by jefftriplett** [comment]
Anything left here let's do in separate PRs. Thanks for the feedback everyone!
