### ISSUE TITLE
All Submissions Can Be Viewed By Any Member

### ISSUE THREAD

**Issue by Miserlou** [djangocon/2016.djangocon.us#110]
Since anybody with an account can join the 'reviewers' team, anybody who wants to can view all of the submissions. Is this intentional?

**Comment by jefftriplett** [comment]
Yes, this is by design, and you can't see reviews on your own submissions. We encourage the community vote on talks and we implemented a double-blind review system. 

Since the deadline ends soon, I updated the page to be invitation based.
