### ISSUE TITLE
Long sponsor URLs don't look pretty

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#111]
The URL for the DSF is long, and it goes off the card. 

<img width="254" alt="screen shot 2016-05-11 at 12 09 13 pm" src="https://cloud.githubusercontent.com/assets/2286304/15193180/664bf39e-1771-11e6-9604-660534ae9c92.png">

**Comment by mightym** [comment]
Thanks! Should be fixed by https://github.com/djangocon/2016.djangocon.us/commit/7fb9b754c889487d473bddffbe19887f11da34bb

**Comment by jefftriplett** [comment]
👍
