### ISSUE TITLE
Update schedule page (First)

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#112]
This has a few parts to it. We need to fix the chosen template so that we can edit schedule slots. This template is: `symposion/schedule/schedule_edit.html`.

You'll need to run the db script to pull from production and it'll set the talks up for you.

You can see the page via: 
- https://2016.djangocon.us/schedule/general-sessions/edit/ (for talks)
- https://2016.djangocon.us/schedule/tutorials/edit/ (for tutorials)

Once you are done, the finalized pages will be here:

- https://2016.djangocon.us/schedule/general-sessions/
- https://2016.djangocon.us/schedule/tutorials/

Last year's template for ideas:

- https://2015.djangocon.us/schedule/general-sessions/

**Comment by jefftriplett** [comment]
This has a few parts to it. We need to fix the chosen template so that we can edit schedule slots. This template is: `symposion/schedule/schedule_edit.html`.

You'll need to run the db script to pull from production and it'll set the talks up for you.

You can see the page via: 
- https://2016.djangocon.us/schedule/general-sessions/edit/ (for talks)
- https://2016.djangocon.us/schedule/tutorials/edit/ (for tutorials)

Once you are done, the finalized pages will be here:

- https://2016.djangocon.us/schedule/general-sessions/
- https://2016.djangocon.us/schedule/tutorials/

Last year's template for ideas:

- https://2015.djangocon.us/schedule/general-sessions/

**Comment by jefftriplett** [comment]
Here is the schedule folder: https://github.com/djangocon/2016.djangocon.us/tree/master/djangocon/templates/symposion/schedule

**Comment by jefftriplett** [comment]
This task replaces #70

**Comment by jefftriplett** [comment]
@mightym any luck with this?

**Comment by mightym** [comment]
yes. I fixed this yesterday. I just added the fix into the development branch. I'm going to continue working now directly in the development branch. I needed to debug that chosen.js stuff outside of the site. But I hope I added everything that is needed. Could you do me a favor and test also if everything works like expected?

**Comment by jefftriplett** [comment]
It looks the same to me: 

![](https://www.evernote.com/l/ABt6DcQzXSBBUoaQgtOdECnrwChXB8RRal8B/image.png)

I'm not sure what else to test?

**Comment by jefftriplett** [comment]
LGTM!
