### ISSUE TITLE
Update talk/tutorial detail page

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#113]
We need to update the talk / tutorial page to match the style of the website. Once you pull a copy of the website, you may access a talk via: http://localhost/schedule/presentation/6/

Here is the presentation detail page: https://github.com/djangocon/2016.djangocon.us/blob/master/djangocon/templates/symposion/schedule/presentation_detail.html

**Comment by jefftriplett** [comment]
This replaces issue #69

**Comment by jefftriplett** [comment]
@mightym / @ipmb we are still seeing issues here: ![](https://www.evernote.com/l/ABuC4Vgx73FNv60Xve1QslM1apwOdNnbmJEB/image.png)

**Comment by ipmb** [comment]
Looks like newlines should be converted in the abstract or possibly use Markdown formatting (assuming there is already a safe implementation or we can trust all the content).

![presentation_ full auto django_ scaling and ha with docker kubernetes and atomic-1](https://cloud.githubusercontent.com/assets/319156/15897227/ec67e862-2d50-11e6-94bb-41efba776755.png)

**Comment by mightym** [comment]
Should be fixed. Added markdown templatetag.
If this is somewhere else an issue use:
```
{% load markitup_tags %}
...
{{ speaker.biography|render_markup|safe }}
```

**Comment by williln** [comment]
Can we left-justify the content in the detail page? Bullets in particular are rendering off-center, and centered paragraphs are harder to read. (Headers are fine centered.) @mightym 
![center](https://cloud.githubusercontent.com/assets/2286304/15938954/7aaaa784-2e2a-11e6-962b-71eb826a4ea0.png)

**Comment by williln** [comment]
(apologies if this is already taken care of, and juts not deployed.)

**Comment by ipmb** [comment]
@williln it wasn't, but I believe it is in d77abc5fffe1e993cd0a04105462e6a5eb0efc15. It's on dev, just need a 👍  and production deploy

**Comment by jefftriplett** [comment]
That sha appears to center it vs. left-justify the text.

**Comment by mightym** [comment]
Its there. Though it doesn't look very good:

<img width="943" alt="bildschirmfoto 2016-06-11 um 12 29 53" src="https://cloud.githubusercontent.com/assets/11863/15984578/37d3c97e-2fd1-11e6-904f-b94611830813.png">

**Comment by ipmb** [comment]
> That sha appears to center it vs. left-justify the text.

It removes it from the content and only applies it to the headers:

![changed text to left align djangocon_2016 djangocon us d77abc5](https://cloud.githubusercontent.com/assets/319156/15985920/f7feb434-2fb8-11e6-94c8-2cc1b07010f9.png)

**Comment by jefftriplett** [comment]
This looks much better. Thank you!
