### ISSUE TITLE
Update speaker profile page

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#114]
We need to style / update the speaker profile page. Once you pull a copy of the website, you may see an example here: 

- with presentations: http://localhost/speaker/profile/7/
- without presentations: http://localhost/speaker/profile/1/

**Comment by jefftriplett** [comment]
Here is the speaker profile template: https://github.com/djangocon/2016.djangocon.us/blob/master/djangocon/templates/symposion/speakers/speaker_profile.html

This replaces issue #75.

**Comment by jefftriplett** [comment]
The Presentation + Presentation Title are the same heading level:

![](https://www.evernote.com/l/ABva128n9RpPS4JjL-eaCkV800e6MeVtPekB/image.png)

**Comment by mightym** [comment]
Is updated and on the development branch
