### ISSUE TITLE
Add URL to repo header

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2016.djangocon.us#118]
Could someone add the live site URL to the top of the repo like it has been done at other times as a convenience?
![untitled](https://cloud.githubusercontent.com/assets/4193054/15714420/07167a14-27e0-11e6-9a33-4b59f6938b1d.jpg)
I do not have access to do this.

**Comment by KatherineMichel** [comment]
N.B. I tried to fix via pull request, but GitHub won't recognize the change, I guess because it's not part of the code base.

**Comment by bmispelon** [comment]
I think I fixed it. Thanks for the heads up :+1: :sparkles:
