### ISSUE TITLE
Schedule List Page

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#119]
There are a few things going on here still: https://2016.djangocon.us/schedule/

- [x] Grid layout is weird
- [x] Can't add tutorials (I'm looking into this one)

**Comment by jefftriplett** [comment]
Might need some advice from @paltman or @brosner about the tutorial problem. @mightym tried to use last year's template too and it didn't help. Our data is modeled after the 2015 and 2014 website so I'm not sure what we are missing.

**Comment by jefftriplett** [comment]
@paltman and @brosner I had to remark approved tutorials as approved again but those work now. Please ignore.

**Comment by jefftriplett** [comment]
@mightym I made a quick pass on @f94723e4f9cee78ca40e7eb937803ef3c845f356 to re-format the schedule like we had last year. This needs styled and your help please.

I think the cache tags were throwing you off so I commented them out for now. We'll want these back in before the page goes out.

**Comment by mightym** [comment]
The last version is on the development branch. Should be good. As soon as all contents are final let me give it a look and see if everything is right

**Comment by jefftriplett** [comment]
I deployed it yesterday afternoon (my time zone). The content is as finalized as we can get until we confirm our locations (that's why the info repeats but that'll be ironed out next week). 

Please confirm that you are happy with it and we can mark this off.

**Comment by jefftriplett** [comment]
I just noticed the backgrounds are slightly different between:

- https://2016.djangocon.us/schedule/
https://2016.djangocon.us/schedule/general-sessions/

**Comment by ipmb** [comment]
I adjusted the class so they two schedules match. The only remaining issue I see is that the footer colors don't match and the warnings at the bottom of the page are difficult to read.

![conference schedule-1](https://cloud.githubusercontent.com/assets/319156/15978046/185b3d56-2f19-11e6-96a1-2f363bd51422.png)

**Comment by jefftriplett** [comment]
I'm re-opening this issue because the text with our "content warning" and "trigger warnings" aren't visible. cc @mightym

**Comment by jefftriplett** [comment]
I'm referring to this page btw: https://2016.djangocon.us/schedule/

**Comment by mightym** [comment]
Should be fixed.

**Comment by mightym** [comment]
One thing, you removed a few day ago the fields where one could see till when a talk ends. I think this was quite useful. I would recommend to add this back. The layout already supports it:

<img width="664" alt="bildschirmfoto 2016-06-11 um 12 26 43" src="https://cloud.githubusercontent.com/assets/11863/15984554/14495ccc-2fd0-11e6-8aa3-eabb503d905a.png">

**Comment by ipmb** [comment]
> I'm re-opening this issue because the text with our "content warning" and "trigger warnings" aren't visible. 

@jefftriplett Were you seeing that on the development branch? I fixed it in 966d09f5e881f43f8bc852a0c14f5c72e9943a08 (and 0b1c39afdc04f0f101679cd30cb24c63125c250d) and verified it was working the staging server shortly after.

**Comment by paltman** [comment]
What does "trigger warning" mean?

**Comment by ipmb** [comment]
https://en.wikipedia.org/wiki/Trauma_trigger#Trigger_warnings

**Comment by jefftriplett** [comment]
@ipmb this page: https://2016.djangocon.us/schedule/

**Comment by paltman** [comment]
Interesting. Thanks.

**Comment by jefftriplett** [comment]
@mightym I re-added "talk ends" and I'm deploying.

**Comment by ipmb** [comment]
@jefftriplett I see it is not working on that page. It _is_ working on staging though, http://my517.us1.eldarioncloud.com/schedule/. Curious to see if your deploy fixes it.

**Comment by ipmb** [comment]
@jefftriplett think we may be seeing EC issues with stale static files getting served again. When I refresh I get old CSS or sometimes none.

/cc @paltman

**Comment by jefftriplett** [comment]
@brosner / @paltman I think @ipmb and I have it down to just needing the static media refreshed which happens every once in a while. Our template changes took a while but they are showing up now.

**Comment by jefftriplett** [comment]
I woke up to a slack notification saying that EC was fixed last night around 11pm. 

Thank you everyone for the response.
