### ISSUE TITLE
Add link to tickets from Tutorials page

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#124]
Along with copy. Suggestion for the top of the page: 

"Tutorials are a separate registration and are $150 per session. [Buy tutorial tickets](https://defna.ticketbud.com/djangocon-us-2016) before they sell out!"

Placement: Between "DjangoCon US Tutorials Schedule" and "July 17" on this page: https://2016.djangocon.us/schedule/tutorials/ 

Thanks to Becca Nock for pointing this out!

**Comment by williln** [comment]
Related to #120 filed by @pydanny which I didn't realize had already been filed! I'll leave this one open since it has the more specific suggestions on placement and wording. Also not sure if Danny's suggestion is for the tutorial schedule page or the detail page.

**Comment by williln** [comment]
Jeff mentioned that the text will show up on the tutorial and talk schedule pages, so something more generic like, 

"Buy your conference and tutorial tickets [here](https://defna.ticketbud.com/djangocon-us-2016)! Tutorials are $150 per session."

**Comment by jefftriplett** [comment]
Most of our the boxes are all or nothing but I have them added. Let me know if something is weird but these changes are deployed.

**Comment by jefftriplett** [comment]
@williln what do you think now?

**Comment by williln** [comment]
LGTM! I'll close.
