### ISSUE TITLE
Dashboard Styles

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#15]
This is the main page that people will see after they have logged in. Any related links / pages need to be styled too.

url: http://localhost/dashboard/

![](https://www.evernote.com/l/ABvSmhokykxMoZvo8YezJFi93Jr0Jy4tt0AB/image.png)

**Comment by jefftriplett** [comment]
@mightym / @ipmb getting the dashboard and proposal submissions are our next priority item (even over the homepage) so that we can take talk proposals for our CFP.

**Comment by jefftriplett** [comment]
@mightym / @ipmb it's closer but we have a double logo at the top: ![](https://www.evernote.com/l/ABumfu0dB21H8KuPb5hpN-e1R9iXHqoNaPQB/image.png)

**Comment by williln** [comment]
Maybe "Create a speaker profile" at the top could be a button, or in larger text, or something? Same for "Apply to be a sponsor" above "Sponsorship"? 

Also, the spacing of "Tutorials" and "General Sessions" and the bullets underneath them is weird, so it visually appears that the "General Sessions" is associated with the bullets above AND below it. Change the spacing such that bullets are grouped in a way that is visually more organized. Make sense?
