### ISSUE TITLE
Symposion Styles

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#16]
The most important are:
- Proposal submissions and related pages
- Speaker and related pages
- Review and related pages

**Comment by jefftriplett** [comment]
Here are the four pages and their location we need to launch the CFP:

## Speaker create page

url: /speaker/create/

## Speaker edit page

url: /speaker/edit/

## Proposal submit

url: /proposals/submit/

## Proposal edit

url: /proposals/submit/talk-45-min/

**Comment by jefftriplett** [comment]
This takes care of the Speaker create / edit page: 

![](https://www.evernote.com/l/ABuufPJixZxI55BnI1-Piq2binxe_XXSoz8B/image.png)

**Comment by williln** [comment]
+1 on Speaker Create/Edit page. Looks done to me.

**Comment by williln** [comment]
Do we want to collect Twitter handles on Speaker profile? Or is that happening elsewhere? Or not at all?

**Comment by jefftriplett** [comment]
The speaker create / edit page looks a little weird still: ![](https://www.evernote.com/l/ABvTO_bdcxNK4rFhF2HSTLGm-jpqdDqMoYIB/image.png). The labels are showing up on the right instead of the left.

cc @ipmb / @mightym

**Comment by williln** [comment]
Also "brief description" is floating there below "audience level" so I think they're not only to the right, there are out of alignment entirely.

**Comment by craigbruce** [comment]
@williln re collecting twitter handles either the proposal or speaker profile I think is preferable to registration since the two are very much disconnected. I'd certainly like to use them on a speaker lists on twitter and add to the guide app.

**Comment by jefftriplett** [comment]
I created ticket #21 and pushed a fix upstream to Symposion.

**Comment by ossanna16** [comment]
@jefftriplett Do you need me to ping Patrick about this or is it fixed and can be closed?

**Comment by jefftriplett** [comment]
@ossanna16 the twitter profile change was merged into Symposion and we deployed it to production. This ticket is still open because we need to update the review templates.

**Comment by ossanna16** [comment]
@jefftriplett Okay :) Let me know if you want me to nag the Pinax people about helping with anything.

**Comment by jefftriplett** [comment]
Closing for smaller tickets. Thank you everyone!
