### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2016.djangocon.us#18]
The README set up instructions are throwing an error for me: ImportError: No module named local

I've tried it several different ways, with virtualenv and pyenv. The instructions for PinaxCon are similar and work perfectly for that project but different file config. I wonder if anyone else has come across this error? 

Update. I wonder if some of the settings at the top of this README got lost in the shuffle and should be there. https://github.com/djangocon/2015.djangocon.us

**Comment by jefftriplett** [comment]
I added an `local.py.example` like we had last year and updated the `README.md`. This changed by accident but we probably never should have had a local.py file in the repo later. I tend to create my own file to avoid accidentally checking something in we don't want / need (which I think is why it was removed). Anyways, it should work now and thanks for reporting it.

**Comment by KatherineMichel** [comment]
Thank you :) Worked perfectly.
