### ISSUE TITLE
Cannot edit content on proposals/submit/talk-25-min/

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#22]
When I try to edit the text on the proposal submission page, it's all greyed out and won't let me edit anything. 
![grey](https://cloud.githubusercontent.com/assets/2286304/13787686/240ab21c-ea9a-11e5-8952-d33304665e17.png)

**Comment by williln** [comment]
Happened when I pressed the edit link while logged in.

**Comment by jefftriplett** [comment]
@mightym this is a much lower priority than the login / registration links.

**Comment by jefftriplett** [comment]
I reported this upstream: https://github.com/pinax/PinaxCon/issues/4

**Comment by jefftriplett** [comment]
I'm tabling this one for now since it's upstream and a ticket exists for it.
