### ISSUE TITLE
Built in admin address is support@example.com

### ISSUE THREAD

**Issue by SaraDGore** [djangocon/2016.djangocon.us#23]
If you go to 'Login' then click to reset your password, the page lists support@example.com as the email to contact. Same thing for once you successfully submit a reset request.

![support](https://cloud.githubusercontent.com/assets/2285473/13794096/363baaa8-eac8-11e5-94a0-0201da6020e2.PNG)

**Comment by jefftriplett** [comment]
Fixed!
