### ISSUE TITLE
Blog sidebar Lorem Ipsum

### ISSUE THREAD

**Issue by SaraDGore** [djangocon/2016.djangocon.us#24]
Generic text remaining in blog sidebar.
![blog_sidebar](https://cloud.githubusercontent.com/assets/2285473/13794699/445ccb78-eacb-11e5-8c3e-f27d6497af0b.PNG)

**Comment by jefftriplett** [comment]
Commented out for now to fix it. @mightym alerting you in case you wanted to switch it out (or maybe it was in the defaults?)

**Comment by mightym** [comment]
Just added it in case we need a place where we want to have an intro text or something else. Can be removed if you think we don't need it.

**Comment by jefftriplett** [comment]
Should we use a `box` there or would we use some of the fields from blog?

**Comment by williln** [comment]
@jefftriplett Do we still need this to be open? Are we thinking of adding something in that box's place? If not, I'm fine closing it (and I don't know what we would add).

**Comment by jefftriplett** [comment]
Good point. Let's close it and @mightym can add something later if he wants.
