### ISSUE TITLE
"Safe" link with no speaker profile

### ISSUE THREAD

**Issue by kennethlove** [djangocon/2016.djangocon.us#27]
Try to [submit a proposal](http://2016.djangocon.us/proposals/submit/) without a speaker profile. The error message displayed near the top of the screen is `To submit a proposal, first <a href='/speaker/create/'>create a speaker profile</a>. ` with the HTML escaped to be safe.

**Comment by SaraDGore** [comment]
![alerts](https://cloud.githubusercontent.com/assets/2285473/13795084/2c8a7412-eacd-11e5-9c53-26e8cb74c22f.PNG)

**Comment by mightym** [comment]
I think this is a symposium issue, right? https://github.com/pinax/symposion/blob/11f697d13757be5505898ae2f5444c394ab3b5ae/symposion/proposals/views.py#L43-L45
Someone a hint for me how I can fix that? :)

**Comment by ipmb** [comment]
Could you use `|safe` wherever the message rendering is defined in the template? Hopefully there isn't anyplace where user input is echo'd back via messages  🤕
