### ISSUE TITLE
Links over blue background need more contrast

### ISSUE THREAD

**Issue by SaraDGore** [djangocon/2016.djangocon.us#3]
The color contrast on links over the blue background (ex: '@DjangoCon' in the mockup) won’t meet WebAIM standards for color contrast.

**Comment by williln** [comment]
The red text on the blue background also fails. And I'm not sure about the red text with white outlining? Red-on-white passes, and white-on-blue passes, but I'm not sure how accessible red text with a white outline on blue is. 
<img width="120" alt="screen shot 2016-02-23 at 10 13 03 am" src="https://cloud.githubusercontent.com/assets/2286304/13261732/53e24b7e-da16-11e5-847d-08120d351e20.png">
<img width="125" alt="screen shot 2016-02-23 at 10 15 29 am" src="https://cloud.githubusercontent.com/assets/2286304/13261745/644a467e-da16-11e5-8c89-374748f2e94a.png">

Screenshot for @SaraDGore's comment as well: 
<img width="88" alt="screen shot 2016-02-23 at 10 15 57 am" src="https://cloud.githubusercontent.com/assets/2286304/13261765/73831224-da16-11e5-89a7-2d0bbe30fede.png">

[Link to Contrast Checker](http://webaim.org/resources/contrastchecker/)

**Comment by jefftriplett** [comment]
Some creative license is fine by me as long as we fix the low hanging fruit like the link style and styles which are hard to read.

**Comment by williln** [comment]
I think the white-outlined text is probably fine, especially if the text is larger, but I'd definitely fix the link @SaraDGore pointed out, and the red-on-blue.

**Comment by jefftriplett** [comment]
I'm re-opening this ticket. The copy isn't readable with the current contrast levels. 

![](https://www.evernote.com/l/ABtpQf-ohptAVZsDH8hzgCZN118dUeggSpMB/image.png)

**Comment by jefftriplett** [comment]
Better but still might need some updates once we have a big sections of copy which we can stage on the dev box.

![](https://www.evernote.com/l/ABvO2zdCZYNN97bmvfPLsKiIf3Eu41hoTU4B/image.png)

**Comment by jefftriplett** [comment]
I think we are good now. Closing. Thanks all!
