### ISSUE TITLE
Can't See Edit Links on Blog Posts

### ISSUE THREAD

**Issue by FlipperPA** [djangocon/2016.djangocon.us#30]
https://2016.djangocon.us/blog/post/1/

I can't see an edit link for the blog post like I can on pages. We're missing an "and":

DEFNA (Django Events Foundation North America), The Django Software Foundation, **and** the Python Software Foundation have each donated to help meet the cost of tickets, travel, and accommodation for attendees who need financial support.

**Comment by SaraDGore** [comment]
Fixed.
