### ISSUE TITLE
"Confirm email" page text is nearly unreadbable

### ISSUE THREAD

**Issue by kojoidrissa** [djangocon/2016.djangocon.us#32]
I just created my account for the 2016 site. The first screenshot is the page I get sent to so I can confirm my email address. I ONLY knew I was on the right page because I saw the "Confirm" button in the upper-left corner. But the text blends in the the background image.
![screen shot 2016-03-15 at 9 39 08 pm](https://cloud.githubusercontent.com/assets/5251109/13800357/8cef6154-eaf6-11e5-9274-fc0a901cef49.png)

It's only visible if I highlight it.
![screen shot 2016-03-15 at 9 39 31 pm](https://cloud.githubusercontent.com/assets/5251109/13800360/8fbb70f8-eaf6-11e5-8cb1-671df38a1507.png)

Contrast that with the "Confirmed" page, where a modal/message box thing" (I should know what that's called) appears and makes the text a bit more obvious.
![screen shot 2016-03-15 at 9 43 02 pm](https://cloud.githubusercontent.com/assets/5251109/13800404/f0e37290-eaf6-11e5-83eb-d535891b0e74.png)

I'm not exactly sure how to fix this, but I'll try to look into it. But, someone who Djangos better than me might do a better job. :-)

**Comment by jefftriplett** [comment]
Thank you for the report!

**Comment by jefftriplett** [comment]
Fixed!

**Comment by craigbruce** [comment]
Is this fix deployed? I got the same issue as @kojoidrissa registering right now

**Comment by jefftriplett** [comment]
![](https://www.evernote.com/l/ABu6jjipHdtLhZHZk1zyXGDUCBwpU2TF7CMB/image.png)

**Comment by craigbruce** [comment]
Great! I also tested this and saw the updated page.
