### ISSUE TITLE
SMTPRecipientsRefused at /account/password/reset/

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#33]
This works locally but not on staging or production.

`{'': (501, 'Recipient syntax error')}`

Request Method:	POST
Request URL:	http://my517.us2.gondor.io/account/password/reset/
Django Version:	1.9.4
Exception Type:	SMTPRecipientsRefused
Exception Value:	
{'': (501, 'Recipient syntax error')}
Exception Location:	/app/.gondor/python/lib/python2.7/smtplib.py in sendmail, line 742
Python Executable:	/app/.gondor/python/bin/python
Python Version:	2.7.11
Python Path:	
['/app',
 '/app/.gondor/python/bin',
 '/app/.gondor/python/lib/python2.7/site-packages/setuptools-19.6-py2.7.egg',
 '/app/.gondor/python/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg',
 '/app',
 '/app/.gondor/python/lib/python27.zip',
 '/app/.gondor/python/lib/python2.7',
 '/app/.gondor/python/lib/python2.7/plat-linux2',
 '/app/.gondor/python/lib/python2.7/lib-tk',
 '/app/.gondor/python/lib/python2.7/lib-old',
 '/app/.gondor/python/lib/python2.7/lib-dynload',
 '/app/.gondor/python/lib/python2.7/site-packages']

**Comment by FlipperPA** [comment]
Are we running the same Python/Django versions on local/stage/prod?

**Comment by bmispelon** [comment]
Reading [`smtplib.py`](https://hg.python.org/cpython/file/2.7/Lib/smtplib.py#l742), this error seems to indicate that you're trying to send an email to an empty address (the keys in the error dict are the email addresses).

Could it be that the user asking for the password reset has no email set?

**Comment by clayball** [comment]
I would try to eliminate issues with the mail server itself first. Can you verify email on prod is actually working.. outside of Python, e.g. using mutt or the mail command?

**Comment by jefftriplett** [comment]
@clayball yes, all other email works fine. We are using https://github.com/pinax/django-user-accounts and honestly haven't had time to really troubleshoot outside of asking for a cursory look from our Pinax friends.

@bmispelon thank you for taking the time to look. It's strange that it works locally, but not in production. I thought it might be related to me creating an account via `createsuperuser` vs. the django-user-accounts flow until @FlipperPA and a few others reported it. I'll see if someone has time to walk through the Pinax code again. (cc @shawninman if you have free cycles)

@FlipperPA yes, the very same.

Thanks everyone!

**Comment by shawninman** [comment]
I may have some free time tomorrow morning, so I'll check back and get my self up to speed on this one.

**Comment by jefftriplett** [comment]
I tested my theory about the Pinax Account + superuser thing and it works for me after I added an Email record. If someone wants to report it upstream then feel free, but I'm guessing it's just a mix of settings and then some of us not having Account records setup which Pinax wants. Thanks again everyone!
