### ISSUE TITLE
Minor: reset password page from email link formatting

### ISSUE THREAD

**Issue by FlipperPA** [djangocon/2016.djangocon.us#35]
The CSS formatting for the Set Your New Password page is wrong / missing.

![image](https://cloud.githubusercontent.com/assets/68164/13822876/b7d37c98-eb7d-11e5-816d-d3150dfea6fb.png)

**Comment by jefftriplett** [comment]
Fixed: ![](https://www.evernote.com/l/ABspHYP4smJLmY0Z8gBRWlkU-WrkItjuWlUB/image.png)
