### ISSUE TITLE
Internal Server Error when trying to review proposals

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#37]
URL I'm trying to visit while logged in: https://2016.djangocon.us/reviews/section/general-sessions/not_reviewed/

Same error on https://2016.djangocon.us/reviews/section/general-sessions/all/

**Comment by jefftriplett** [comment]
This may be a data issue <or> it maybe an upstream Symposion issue <or> project configuration issue.

**Comment by shawninman** [comment]
@jefftriplett how can I get the proper permissions to view this page? My user account is shawninman

**Comment by jefftriplett** [comment]
@shawninman fixed! Thanks for looking!

**Comment by shawninman** [comment]
@jefftriplett I don't have access to the production admin, but the issue is that two _Sections_ have the same slug. If you change the slug on the "Tutorials" section, things snap back into place. 

admin/symposion_conference/section/2/change/

**Comment by jefftriplett** [comment]
@shawninman permission and slug fixed. I clearly could not see an obvious problem. thank you for figuring it out!

**Comment by jefftriplett** [comment]
This was the fixture btw: https://github.com/djangocon/2016.djangocon.us/commit/231acdb84702e99938d386450025f5ab81ea39ed

**Comment by shawninman** [comment]
Makes sense. It didn't occur to me that the issue was in a fixture until you asked me about it.
