### ISSUE TITLE
"Edit Page" says "Create Page" in title 

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#38]
This is obviously NOT a big deal and is a very low priority. But it gave me a tiny heart attack when I was editing a page and thought I'd somehow erased the page that was there before. 
<img width="741" alt="screen shot 2016-03-17 at 10 39 42 am" src="https://cloud.githubusercontent.com/assets/2286304/13855251/b2131b88-ec2c-11e5-8e4b-6ab47dd4832c.png">

**Comment by jefftriplett** [comment]
@KatherineMichel want to take this one?

**Comment by KatherineMichel** [comment]
Yes @jefftriplett !

**Comment by jefftriplett** [comment]
Here's the line causing the confusion: https://github.com/djangocon/2016.djangocon.us/blob/master/djangocon/templates/pinax/pages/page_edit.html#L10

If it saves @williln a :broken_heart: then I'm all for it.

**Comment by KatherineMichel** [comment]
I thought I fixed this in the development branch. Won't it be merged with the master branch?

**Comment by jefftriplett** [comment]
You are right! I thought you had but I was browing github using the master branch instead of the development branch. Thanks again, ignore me :)
