### ISSUE TITLE
Separate out "here's what you can do"

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#4]
At the moment, the suggestions for what you can do between now and when we announce are sort of jumbled together. I suggest separating them out in this way: 

> Mark your calendars and help us spread the word! Start thinking about topics for when our Call for Proposals is announced. 

> Watch this space and @DjangoCon on Twitter. Want to help  by joining our organizers? Follow the discussions on the djangocon-organizers list. 

> Sponsor the event! 

> We hope we'll see you at DjangoCon US!

**Comment by KatherineMichel** [comment]
I agree. Would be better to separate out to bring more attention to calls to action.
