### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by andyosuna** [djangocon/2016.djangocon.us#41]
Increase font size to 16 px or 1.2 em to better readability.

**Comment by mightym** [comment]
Base font size is already 16px.
```
$font-size-root:             16px !default;

$font-size-base:             1rem !default;
```

**Comment by andyosuna** [comment]
The Oficina font is less readable than Georgia, if you were to increase the `$font-size-root` by one or two pixels it makes a huge difference on readability :)

**Comment by jefftriplett** [comment]
Sorry for the delay here. Mark bumped the default fonts up and we verified that the website is zoom friendly and readable in case it needs bumped up. I have bad eyes and I tend to do this on most website I visit.
