### ISSUE TITLE
"Questions? Comments?" in footer is invisible, has wrong header tag

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#43]
It's not invisible as CSS, but it's the same color as the background. 
<img width="700" alt="screen shot 2016-03-17 at 6 06 02 pm" src="https://cloud.githubusercontent.com/assets/2286304/13865670/ff3c711e-ec6a-11e5-8f2c-8ac6a1902916.png">

Also, ```<h5>Questions? Comments?</h5>``` is what's rendering in the footer. The html or markdown is treating this as a header. We should use a CSS class instead, since different pages will have different headers. Having headers out of order can affect screen readers.

**Comment by KatherineMichel** [comment]
I worked on a fix for this. It's an improvement, but not sure it's acceptable. I used interim-teaser and h3. I tried to create an original block in _type.scss with h5 instead, but for some reason, not working, even when I run make all. 

![screen shot 2016-03-19 at 5 47 08 pm](https://cloud.githubusercontent.com/assets/4193054/13901894/2404033a-ee01-11e5-9533-0a6042616c3b.png)
![screen shot 2016-03-19 at 6 12 55 pm](https://cloud.githubusercontent.com/assets/4193054/13901898/686065c8-ee01-11e5-9de2-81d42a111c00.png)

**Comment by jefftriplett** [comment]
Thanks for taking a look at it. I'm cc'ing @mightym to take a look after he's done with the overall look of the website.

**Comment by williln** [comment]
@KatherineMichel This is certainly an improvement! I love being able to see "Questions? Comments?" now! Thank you! :bouquet: Will leave open for now per Jeff.

**Comment by mightym** [comment]
I'm sorry. I actually did some fixes there a few days ago. Currently this looks like:
<img width="568" alt="bildschirmfoto 2016-03-22 um 12 20 50" src="https://cloud.githubusercontent.com/assets/11863/13949990/a383b9b0-f028-11e5-80a2-9eb7bf3a7cbe.png">
I'm closing this. Feel free to reopen when this is not what you have been looking for.

**Comment by williln** [comment]
LGTM! Thanks @mightym and @KatherineMichel! :dolphin:
