### ISSUE TITLE
Blank slanted-page background images

### ISSUE THREAD

**Issue by shawninman** [djangocon/2016.djangocon.us#44]
There are some background images appearing on pages using the Symposion base template. I think maybe these are related to last year's templates? If you have trouble finding them, try expanding your browser window width, or try zooming out (CMD & -) a few steps.
![screen shot 2016-03-18 at 6 06 38 am](https://cloud.githubusercontent.com/assets/216237/13874696/e2476f4a-eccf-11e5-9428-55847dc5c23c.png)

**Comment by jefftriplett** [comment]
Thanks for reporting. We asked to prioritize functionality over polishing off the overall design. So some of the "missing design" issues will be fixed in the next week or so.
