### ISSUE TITLE
Misplaced blue gradient on the home page

### ISSUE THREAD

**Issue by shawninman** [djangocon/2016.djangocon.us#45]
I can't tell for sure whether it's on purpose, but the blue gradient above the home page stitching either seems to be misplaced or improperly sized... Also, it seems to have some heavy JPG artifacts. Should this be here?
![screen shot 2016-03-18 at 6 16 55 am](https://cloud.githubusercontent.com/assets/216237/13875003/9ebb9042-ecd1-11e5-936a-a459100e0b44.png)

**Comment by bmispelon** [comment]
It seems to come from https://github.com/djangocon/2016.djangocon.us/blob/master/client/scss/common/_poster.scss#L23 which was added in a6c32505dfd9d6dd59b7e756316b0b6d36251c36.

It seems to be there on purpose but I'm not sure what it's doing (in any case, the background image used is only 1080px wide which doesn't seem enough).

**Comment by ipmb** [comment]
It's part of the design which is still WIP... have patience :)
