### ISSUE TITLE
Submitted proposals show "Track" field, which we are not using. 

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#48]
This is likely to be confusing to people who look at their proposals after submitting. 

![proposal](https://cloud.githubusercontent.com/assets/2286304/13882753/10adaed0-ece4-11e5-8fda-06bf74cf1950.png)

**Comment by jefftriplett** [comment]
This change involves submitting a patch to remove `Track` from these templates: https://github.com/djangocon/2016.djangocon.us/search?utf8=%E2%9C%93&q=Track

**Comment by clayball** [comment]
I'm dipping my toes into Django.. this would be a good exercise for me. I'd be happy to take this on. I should have some time this evening to create a patch.

**Comment by jefftriplett** [comment]
@clayball Sounds great, thank you!

**Comment by clayball** [comment]
I created a patch. What's the protocol for adding/submitting patched? Should I gzip it and upload?

**Comment by ossanna16** [comment]
@clayball Submitting a pull request would be great. Thank you so much! :)

**Comment by b3h3rkz** [comment]
This is supposed to be closed right?

**Comment by KatherineMichel** [comment]
Looks like it was just merged and can be closed now #53
