### ISSUE TITLE
Required proposal fields are not marked 

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#50]
Can we mark them?

**Comment by bmispelon** [comment]
For DjangoCon Europe, we use this trick to add a `*` in the label and a `required` HTML attribute on the field: https://github.com/djangocon/2016.djangocon.eu/blob/master/cfp/forms.py#L64-L70

**Comment by mightym** [comment]
Will try to find a solution here. Just realized that the whole form validation/error handling is currently removed from bootstrap https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L304-L377

**Comment by sul4bh** [comment]
This is not "up-for-grabs" but I have fixed this. Please see the screenshot below.
![required_and_error](https://cloud.githubusercontent.com/assets/109486/13936731/135dda60-ef96-11e5-9077-83f1920053ef.png)

Let me know what you think and I will create a PR.

**Comment by williln** [comment]
@sul4bh I like it! Please create a PR. If @mightym already has a fix in progress, we can deal with that too.

**Comment by sul4bh** [comment]
@williln Just created. I have used @bmispelon hack for adding a '*'.

**Comment by williln** [comment]
Closing this since it was merged. Thank you so much, @sul4bh! :sparkles:

**Comment by sul4bh** [comment]
Glad I could help @williln
