### ISSUE TITLE
Fix background on proposal review page

### ISSUE THREAD

**Issue by ossanna16** [djangocon/2016.djangocon.us#54]
Right now when I go to the proposal review page to score proposals I see this

![bildschirmfoto 2016-03-20 um 09 13 06](https://cloud.githubusercontent.com/assets/8700795/13903448/32091454-ee7c-11e5-8fea-170db5839d45.png)
![bildschirmfoto 2016-03-20 um 09 13 31](https://cloud.githubusercontent.com/assets/8700795/13903449/34170f9e-ee7c-11e5-916d-88e172b0ba21.png)

Half the page is basically unreadable, which makes it really hard to review proposals. Could we either make the wide background bigger or change the formatting of the text somehow so it actually stays within the white background?

**Comment by jefftriplett** [comment]
Thanks for reporting this issue. This is one @mightym's list to fix this week along with Sponsorship updates. I'm closing the issue because it's "next on the list" and outlined in the update email I sent this week.

**Comment by ossanna16** [comment]
Sorry, I missed it in your update email. And thank you @mightym for working on this. I appreciate it :)

**Comment by mightym** [comment]
Oh ... sorry haven't seen that template before :) which url/template is this? Do I need some specials rights for the user to see it?

**Comment by jefftriplett** [comment]
This is all part of https://github.com/djangocon/2016.djangocon.us/tree/master/djangocon/templates/symposion/reviews (specifically it's the `review_list.html` template, but every template in this folder needs verified). Ping me if you have more questions (it's in the dashboard under *Reviews*).
