### ISSUE TITLE
virtualenvwrapper hangup

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2016.djangocon.us#6]
I was playing around with the development branch to run via local server. I have a Mac running El Capitan. I had never used virtualenvwrapper before. When I attempted to install it, there was an error that apparently had to do with the version of six that is part of Apple's pre-installed version of Python 2.7. The error is documented here: https://github.com/pypa/pip/issues/3165. I was able to install virtualenvwrapper using the workaround. I'm putting this here because it might be helpful for others to know if someone has a problem setting it up on a local server, but also because I would like to have the option to contribute. I have the pre-installed six 1.4.1 version installed now instead of the latest version. Does anyone know if this will cause a problem to contribute, or is it beside the point now?

**Comment by jefftriplett** [comment]
Thank you for opening an issue. I would recommend using [pyenv](https://github.com/yyuu/pyenv) to install a newer Python and [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv) to get around any system level issues.

The development branch is in a weird state with the 2016 splash page files with a copy of last year's website. I'm hoping that by this time next week, everything will be in place, we'll update the README, and open some issues for new contributors. Until then, we're kind of waiting for the design to be complete and integrated with Symposion.

**Comment by KatherineMichel** [comment]
Thank you for the info. Looks like it can be installed via Homebrew. I will take a look.

**Comment by jefftriplett** [comment]
:+1: I hope this means the newer version just works :)

**Comment by KatherineMichel** [comment]
Yep, pyenv worked and I think it is better than before :) I still had a conflict with pyenv-virtualenv and workon command from the prior README, but it looks like that might be moot now anyway. I will go back and look at that later.

**Comment by KatherineMichel** [comment]
pyenv-virtualenv (and pyenv-virtualenvwrapper) seem to be working great today. Don't know what was wrong the other day. Maybe did something in the wrong order. :)

**Comment by jefftriplett** [comment]
It could be the difference between opening a new tab vs. reusing an old once since pyenv-virtualenv + pyenv-virtualenvwrapper and virtualenv + virtualenvwrapper have some subtle differences.
