### ISSUE TITLE
"Contact Us" goes to wrong email account

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#67]
The messages sent to "Contact Us" from https://2016.djangocon.us/contact/ go to errors@defna.org. They **should** go to hello@djangocon.us.

**Comment by jefftriplett** [comment]
Fixed in: https://github.com/djangocon/2016.djangocon.us/commit/b02a232265156d2360a4723c8cf9b5c979508631 Deploy now.

Thank you for reporting / catching it! :sparkles:
