### ISSUE TITLE
Website footer?

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#7]
What links do we want in the website's footer?

Last year we had:
> Questions? Comments?
> Contact Us
> Design + Build by [Lincoln Loop](https://www.lincolnloop.com/)
> Hosted on [Gondor](https://gondor.io/)
> Presented by [DEFNA](http://defna.org/)
> ©2016 DjangoCon

![](https://www.evernote.com/l/ABtLysGRewxBNJ1bWr7MyPOaKTbMi3SJx2kB/image.png)

**Comment by craigbruce** [comment]
Seems like they cover all the bases

**Comment by jefftriplett** [comment]
We have one which works for now :)
