### ISSUE TITLE
Internal Server Error when clicking on proposal title

### ISSUE THREAD

**Issue by ossanna16** [djangocon/2016.djangocon.us#76]
When I click on the title of any of my submitted proposals I get an Internal Server Error. Last week when I submitted my proposals this seemed to work fine. I can also edit my proposal (or at least I think I can, I clicked the edit button but haven't actually tried making changes and submitting them), just clicking on the title gives me an error.  /cc @jefftriplett @mightym

**Comment by jefftriplett** [comment]
Fixed too. Thanks again!
