### ISSUE TITLE
Can't see list of submitted proposals anymore

### ISSUE THREAD

**Issue by ossanna16** [djangocon/2016.djangocon.us#77]
I can't see the list of submitted proposals anymore when I attempt to review them. Last week this worked fine. When I click on "General Sessions" and then "All" I see this 

![bildschirmfoto 2016-03-23 um 15 05 38](https://cloud.githubusercontent.com/assets/8700795/13987625/c0038896-f108-11e5-92f4-843c0e2cbf18.png)

The same applies to tutorials. /cc @jefftriplett @mightym

**Comment by jefftriplett** [comment]
Fixed. I'm just slow to close the ticket. Thanks for reporting it!
