### ISSUE TITLE
Logo blocks top menu items

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#78]
When the logo floats over the menu it causes the items to be non-clickable. 

![](https://www.evernote.com/l/ABsp0v3Mcf9D6Kd19RExQgyw6sYlve2JBxAB/image.png)

**Comment by craigbruce** [comment]
You beat me to it! I also see this behaviour.

**Comment by mightym** [comment]
Thats on production right? On dev this is fixed (based on the menu item count there) need to adjust that just at the end on the final nav size.

**Comment by mightym** [comment]
Or actually that should already be fixed for every amount of menu items, see here on dev:
<img width="1234" alt="bildschirmfoto 2016-03-24 um 20 39 01" src="https://cloud.githubusercontent.com/assets/11863/14029115/8f97b756-f200-11e5-9aa8-5bb549649f6d.png">

**Comment by jefftriplett** [comment]
Deployed and fixed! Thanks again @mightym
