### ISSUE TITLE
Content pages: vertical padding for headers

### ISSUE THREAD

**Issue by FlipperPA** [djangocon/2016.djangocon.us#79]
The vertical heading on headers seems reversed, which makes it appear like a header is part of the previous paragraph rather than the one it is heading:

https://2016.djangocon.us/venue/

In the link above, "PHILADELPHIA IS AMAZING!" appears to be lumped with the previous paragraph (ON A BUDGET?), as an example, rather than the paragraph is leads ("Philly has fantastic food...").

**Comment by mightym** [comment]
Fixed this. Fien for now. I will work on an issue with headlines though

**Comment by jefftriplett** [comment]
Thanks!
