### ISSUE TITLE
User media uploads are broken

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#83]
We need a plugin or way to get user uploads to be persistent. Cc'ing @brosner since he volunteered to help.

**Comment by brosner** [comment]
Update: I am almost done with the storage backend to use native GCS libraries. I should have the PR ready to go in the next couple of hours.

**Comment by brosner** [comment]
PR is up: #85

**Comment by jefftriplett** [comment]
@brosner looks like it's working! Thanks again for all the hard work!
