### ISSUE TITLE
Mobile: Where should we put the buy ticket call to action?

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#84]
Random feedback:

> I hope this comes off constructive (or possibly I'm totally just missing it) - 
> it was really difficult for me on my iPhone 6s to find buy tickets call to
> action.
>
> From the homepage being tweeted I clicked on register which was possibly to
> hasty so then I clicked on tickets which landed me on a page with lots of
> text and eventually I scrolled to find a text link that lead to the tickets
> purchase page.

**Comment by jefftriplett** [comment]
@mightym this is more of a question of do we add a "buy tickets" menu item or what should we do to make this more obvious?

**Comment by craigbruce** [comment]
I'd agree it is hard to find the text CTA to buy tickets, especially on a mobile browser. What about a button in the menu bar like the Register/Login, but "Buy Tickets" or similar.

**Comment by mightym** [comment]
I just added a "buy tickets" button to the navigation. What is the link/url to buy tickets?

**Comment by jefftriplett** [comment]
@mightym https://defna.ticketbud.com/djangocon-us-2016

**Comment by jefftriplett** [comment]
@mightym thanks again for the fix!
