### ISSUE TITLE
Speaker Export View (need before 4/19)

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#88]
We need a view to export Speaker details so that we may contact them more easily.  These are the requirements:

1. This view should [live here](https://github.com/djangocon/2016.djangocon.us/blob/development/djangocon/views.py)

2. The view should generate a downloadable (CSV file) of [Symposion Speaker records](https://github.com/pinax/symposion/blob/master/symposion/speakers/models.py#L16) including:
 - [ ] Name
 - [ ] Email address ([located here])(https://github.com/pinax/symposion/blob/master/symposion/speakers/models.py#L66)

3. The view should only be accessible by `superusers`.

4. Run it by @SaraDGore for approval

**Comment by sul4bh** [comment]
Based on 2015 code (https://github.com/djangocon/2015.djangocon.us/blob/develop/djangocon/views.py#L231), we might need unicodecsv package for this task.

**Comment by chromakey** [comment]
My understanding is that the Python 3 CSV module supports unicode, but I'm happy to convert it to unicodecsv if necessary.

**Comment by jefftriplett** [comment]
Thanks for the contributions on this. We can wrap it in unidecode to get us by if need be then fix it on the other side.
