### ISSUE TITLE
Port 2015 tools to 2016 website

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#89]
We need to port our 2015 tools into the 2016 code base. This allows Guidebook and some of our other tools to work properly.

These are the requirements:

1. **Update Views:** [2015 views](https://github.com/djangocon/2015.djangocon.us/blob/develop/djangocon/views.py) into the [2016 views](https://github.com/djangocon/2016.djangocon.us/blob/development/djangocon/views.py).

2. **Update Urls:** We need to port all of the `djangocon.views.*` views from the [2015 website](https://github.com/djangocon/2015.djangocon.us/blob/develop/djangocon/urls.py) into the [2016 website](https://github.com/djangocon/2016.djangocon.us/blob/development/djangocon/urls.py)

3. Add missing requirements to our project's [requirements.txt](https://github.com/djangocon/2016.djangocon.us/blob/development/requirements.txt). (possibly: `unidecode`, `tablib`, `unicodecsv`, ...)

4. Adjust Symposion imports which might have changed. Example: [Biblion](https://github.com/djangocon/2015.djangocon.us/blob/develop/djangocon/views.py#L5) is now [Pinax-Blog](https://github.com/pinax/pinax-blog/blob/master/pinax/blog/models.py#L60)

5. **Update View Security**: Update `@login_required` views to only allow `superuser` access. [Example 1](https://github.com/djangocon/2015.djangocon.us/blob/develop/djangocon/views.py#L35) and [Example 2](https://github.com/djangocon/2015.djangocon.us/blob/develop/djangocon/views.py#L230).

**Comment by sul4bh** [comment]
I can work on this. Here is my plan of action:

1. Add missing requirements
1. Adjust imports
1. Update Views
1. Update view Security
1. Update Urls

What do you guys think about having a **https://2016.djangocon.us/data** page(accessible to superusers only) that has a list of all downloadable CSVs? It will save us from having to remember the CSV urls.

**Comment by jefftriplett** [comment]
@sul4bh great idea, that'd be perfect!

**Comment by sul4bh** [comment]
I ran into an issue regarding pinax-symposium and have submitted an issue upstream (https://github.com/pinax/symposion/issues/131). I am hoping to hear from them soon.

Do we need schedule_json() and guidebook_news_feed() for 2016?

**Comment by jefftriplett** [comment]
@sul4bh Thanks for the update. The `Sponsor.objects.active()` call can be changed to `Sponsor.objects.filter(active=True)` if that gets you past a blocker. Ultimately fixing Symposion upstream though helps everyone so thank you for opening that issue.

Yes, we do need `schedule_json` and `guidebook_news_feed` for Guidebook and the Program Guide integration. Hopefully, updating the Biblion references to use Pinax-Blog is just switching imports. 

Let me know if you have questions and thanks again!

**Comment by sul4bh** [comment]
Thanks for the tips Jeff. Just created pr #93

**Comment by jefftriplett** [comment]
Thanks again!
