### ISSUE TITLE
Bar below footer.

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2016.djangocon.us#9]
There's a transitional graphic which doesn't quite match up to the bottom of the page. See here:

![](https://www.evernote.com/l/ABuRDgQ_IvJHRas2XZRKM9afIdpx1pug0rUB/image.png)

Maybe this is related to #7?

**Comment by jefftriplett** [comment]
it looks better with the footer but doesn't quite look right to me. What am I missing? 

![](https://www.evernote.com/l/ABu0E4MHD8xD3rZ0hZ_maFOlIhiFbvpb3c0B/image.png)

**Comment by b3h3rkz** [comment]
![footercon](https://cloud.githubusercontent.com/assets/9025305/13556913/eca1e156-e3dc-11e5-9fa5-531853f24793.png)

@jefftriplett  Would you have preferred it centered this way or to not show at all?

**Comment by jefftriplett** [comment]
@b3h3rkz My apologies, I should have closed this already. It's a paper fold affect.

**Comment by b3h3rkz** [comment]
Great
