### ISSUE TITLE
Expired password reset token page not clear

### ISSUE THREAD

**Issue by b3h3rkz** [djangocon/2016.djangocon.us#94]
I don't think this is of much importance but thought I should bring it to your notice anyways.
The page for expired password reset tokens does not properly display the error message.
![djangocon](https://cloud.githubusercontent.com/assets/9025305/14383811/f7255676-fd86-11e5-934c-7dd4f7b96e6b.png)

**Comment by jefftriplett** [comment]
Merged, thank you!
