### ISSUE TITLE
Animated background image represents accessibility issue

### ISSUE THREAD

**Issue by freakboy3742** [djangocon/2016.djangocon.us#97]
I know the Phillie Phanatic is an important local icon, and seeing him (her? it?) dance is part of the crazy image, but the animated image in the website is a significant accessibility issue for anybody with ADHD or who is on the Autism spectrum. 

I'm only mildly affected by these problems, but having the page open on my desktop to edit a proposal is proving extremely difficult due to the distraction posed by the animation.

Might I suggest replacing the animation with a static image? Or, at least, a GIF if that only has one loop?

**Comment by ipmb** [comment]
For a possible short term fix, you can make your window smaller to hide the background.

**Comment by williln** [comment]
I'm +1 on this. @mightym Can you fix?
