### ISSUE TITLE
Add talk time (45/25 minutes) to Proposal Details tab

### ISSUE THREAD

**Issue by SaraDGore** [djangocon/2016.djangocon.us#98]
When reviewing a proposal, it helps to know if it's a 25 minute or 45 minute talk. Currently that only shows up on the listing screen and not on the proposal details themselves.

Ex:
https://2016.djangocon.us/reviews/review/41/
(Note that this talk has the minutes in the title of the talk itself.)

**Comment by jefftriplett** [comment]
Places to add this info to the template:

- https://github.com/djangocon/2016.djangocon.us/blob/development/djangocon/templates/symposion/proposals/_proposal_fields.html
- https://github.com/djangocon/2016.djangocon.us/blob/development/djangocon/templates/symposion/proposals/_pending_proposal_row.html

**Comment by jefftriplett** [comment]
I think we did this
